### ISSUE TITLE
[FEAT] 신고조회 기능 구현

### ISSUE THREAD

**Issue by sami355-24** [GDSC-KNU/3rd-sc-ex1-CitySavior-Backend#5]
## Description 📝
1. `단일 신고 조회 기능`
DB로 부터 단순 조회입니다.

2. `지도에서 신고현황 조회 기능`
요청 파라미터로부터 인근에 존재하는 신고 정보를 반환하는 기능입니다.

### 
**DB변경**
파라미터로 넘어오는 위도 경도 즉 공간정보를 바탕으로 로직을 수행해야 하는데 이를 직접 구현하는 방법에는 두가지가 있습니다.
하나는 테이블에 존재하는 모든 엔티티를 가져와 브루트포스로 연산을 하는것이고
나머지 하나는 직선 거리가 아닌 수직 거리들을 합하는 방법인 Manhattan Distance로 계산하여야 합니다. 

그러나 첫번째 방법은 시간, 메모리 리소스를 많이 잡아먹기에 **현실적인 어려움**이 있으며
두번째 방법은 **부정확한 결과**를 반환한다는 단점이 존재합니다.
그렇기에 직접 구현하는 것이 아닌 저희가 원하는 로직, 즉 GIS 로직을 제공해주는 **PostgreSQL**의 **PostGIS**를 사용하는 것이 좋아보입니다

## To-Do ☑️
- [x] 단일 신고 조회해서 반환하기
- [x] MySQL에서 Postgre로 DB변경
- [x] 위도, 경도를 Point 객체로 변경
- [x] DB로부터 GIS 함수를 이용해 조회한후 반환하기

## Reference 📚
https://gksdudrb922.tistory.com/246
https://velog.io/@sdsd0908/%EC%8A%A4%ED%94%84%EB%A7%81-%EB%B0%98%EA%B2%BD-%EA%B2%80%EC%83%89-%EA%B8%B0%EB%8A%A5-DB-%EB%B3%80%EA%B2%BD%EC%97%90-%EB%8C%80%ED%95%9C-%EA%B3%A0%EB%AF%BC
