### ISSUE TITLE
[FEAT] '신고 완료', '신고 댓글 작성', '신고 통계 목록' 

### ISSUE THREAD

**Issue by sami355-24** [GDSC-KNU/3rd-sc-ex1-CitySavior-Backend#7]
## Description 📝
'신고'라는 도메인에 대한 주요 로직은 구현하였습니다. (#1 #5 )
그렇기에 해당 이슈에서는 아래와 같은 내용을 구현합니다.

1. '신고'한 장소에 대한 수리를 마치고 완료처리를 해주는 로직인 '신고 완료'
2. '신고'한 장소에 대한 의견을 나눌 수 있는 로직인 '신고 댓글 작성'
3. 임의의 경도 위도 인근에 존재하는 '신고'에 대한 통계 목록

## To-Do ☑️
- [x] 신고 완료 로직 - 신고 완료한 시각으로 수리된 날짜를 갱신하는 로직 구현
- [x] 신고 댓글 작성 - 신고 댓글을 의미하는 새로운 엔티티를 생성하고 연관관계를 맺을 수 있게 로직 구현
- [x] '신고'에 대한 통계 목록 - 반경 검색을 하고 해당 결과 값을 집계함수를 통해서 원하는 값 반환할 수 있도록 로직 구현
